### ISSUE TITLE
[Bug]: Param auto_id must be bool type, however the default value of auto_id is `None`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/pymilvus#1182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Param auto_id must be bool type, however, the default value of auto_id is `None`,

### Expected Behavior

```
   name: uid
    description: 
    type: 5
    is_primary: True
    auto_id: None

```
<AutoIDException: (code=1, message=Param auto_id must be bool type.

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```
