### ISSUE TITLE
Questions about IndexIVFPQ search time

### ISSUE THREAD

**Issue by AyushP123** [milvus-io/pymilvus#195]
Hi, 

Thank you for your hard work in creating pymilvus. I ran a search on an Database of 30 million vectors indexed with IVFPQ. Here are the results:

Search with query of size 20k vectors takes around 59 seconds for the complete search.
Search with a query of size 1 vector takes 4.5 seconds.

```
from milvus import Milvus, IndexType, MetricType, Status
import numpy as np
import time

client = Milvus(host='localhost', port='19530')
client.connect()
collection_name = "test_01"
param = {'collection_name':collection_name, 'dimension':256, 'index_file_size':1024, 'metric_type':MetricType.L2}
client.create_collection(param)

for i in range(3000):
    vectors = np.random.rand(10000, 256).astype("float32")
    client.insert(collection_name=collection_name, records=vectors)

index_param = {
        "m": 16,
        "nlist": 1024
        }
status = client.create_index(collection_name, IndexType.IVF_PQ, index_param)

search_param = {
        "nprobe": 100
        }
start = time.time()
status, result = client.search(collection_name, 200, query_vectors, params=search_param)
end = time.time()
print("Search Time " + str(end - start))

for i in range(10):
    query_vector = np.random.rand(2, 256).astype("float32")
    start = time.time()
    status, result = client.search(collection_name, 200, query_vector, params=search_param)
    end = time.time()
    print("Search Time " + str(end - start))

client.disconnect()
```

**Comment by tinkerlin** [comment]
The batch search always fast than single query search.  But if you do lots of single search at the same time, the qps will become better.

@AyushP123

**Comment by AyushP123** [comment]
Hi @tinkerlin, Thank you for your response. I tried iterating 100 times instead of 10 and the search time didn't decrease from an average of 4.5. These are the relevant parameters I have set through 
`server_config.yaml`. I suspect that there is a read happening every time I run a query. Its definitely not an issue with IVFPQ as I tried a similar experiment with FAISS IVFPQ and got an response time of around 2 millisecond ( which is consistent with the search time I am getting through 20k vectors ).
```
db_config:
  backend_url: sqlite://:@:/
  preload_collection: '*'
  auto_flush_interval: 1

cache_config:
  cpu_cache_capacity: 11
  insert_buffer_size: 10
  cache_insert_data: true

engine_config:
  use_blas_threshold: 1
  gpu_search_threshold: 1

gpu_resource_config:
  enable: true
  cache_capacity: 4
  search_resources:
    - gpu0
  build_index_resources:
    - gpu0
```
